trigger:
- none

pool:
  name: Pool_Name

steps:

- task: SonarQubePrepare@4
  displayName: Prepare Analysis Configuration task
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectVersion=1.0.0.0
      sonar.projectName=springsonarqube
      sonar.sources=src/main/java/
      sonar.language=java
      sonar.sourceEncoding=UTF-8
  enabled: true


- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.SourcesDirectory)/sonarqube/sonarqubespring/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
  enabled: true

 
- task: SonarQubePublish@4
  displayName: Publish Quality Gate Result
  inputs:
    pollingTimeoutSec: '300'
  enabled: true
